version: '3.8'

services:
  camunda:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda-bpm
    ports:
      - "8080:8080"
    networks:
      - ed-network

networks:
  ed-network:
